name: API Test Workflow

on:
  push:
    branches:
      - '*'
    workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load Docker image
        run: docker load -i api_testing_service_latest.tar.xz

      - name: Start Docker container
        run: docker run -d -p 8900:8900 --name apiservice api_testing_service

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean test -Dtest=ParallelRunnerTest --file pom.xml

